# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: greetapi
  boot:
    admin:
      client:
        url: http://localhost:3333/
        enabled: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
    access:
      default: read-only
  endpoint:
    health:
      show-details: 'always'
logging:
  level:
    org:
      springframework:
        web: INFO
        boot:
          autoconfigure: INFO
